"""Add Epic/Issue relationship

Revision ID: 401216b38449
Revises: 0f92b1e2efd8
Create Date: 2021-08-10 12:28:07.401315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401216b38449'
down_revision = '0f92b1e2efd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'epics', ['EpicId'], ['Id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
