"""Initial creation of epics and issues

Revision ID: 73435615430b
Revises: 
Create Date: 2021-08-09 17:11:50.693045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73435615430b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epics',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Key', sa.String(), nullable=True),
    sa.Column('Summary', sa.String(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('issues',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Key', sa.String(), nullable=True),
    sa.Column('Summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues')
    op.drop_table('epics')
    # ### end Alembic commands ###
