"""Add Issue estimate

Revision ID: b414813f0191
Revises: 401216b38449
Create Date: 2021-08-10 12:49:37.262363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b414813f0191'
down_revision = '401216b38449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('Estimate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'Estimate')
    # ### end Alembic commands ###
