"""Add sprints and association tables

Revision ID: c15a7e39a9d3
Revises: b414813f0191
Create Date: 2021-08-20 17:08:32.494109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15a7e39a9d3'
down_revision = 'b414813f0191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('JiraId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_sprints'))
    )
    op.create_table('epics_to_versions',
    sa.Column('EpicId', sa.Integer(), nullable=True),
    sa.Column('VersionId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EpicId'], ['epics.Id'], name=op.f('fk_epics_to_versions_EpicId_epics')),
    sa.ForeignKeyConstraint(['VersionId'], ['fixversions.Id'], name=op.f('fk_epics_to_versions_VersionId_fixversions'))
    )
    op.create_table('issues_to_sprints',
    sa.Column('IssueId', sa.Integer(), nullable=True),
    sa.Column('SprintId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['IssueId'], ['issues.Id'], name=op.f('fk_issues_to_sprints_IssueId_issues')),
    sa.ForeignKeyConstraint(['SprintId'], ['sprints.Id'], name=op.f('fk_issues_to_sprints_SprintId_sprints'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues_to_sprints')
    op.drop_table('epics_to_versions')
    op.drop_table('sprints')
    # ### end Alembic commands ###
