"""Support natural sort on epics

Revision ID: f9cccabb45c3
Revises: c15a7e39a9d3
Create Date: 2021-09-02 07:54:01.722338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cccabb45c3'
down_revision = 'c15a7e39a9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epics', sa.Column('SortOrder', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('epics', 'SortOrder')
    # ### end Alembic commands ###
